### ISSUE TITLE
Question about getting data into react

### ISSUE THREAD

**Issue by blenet** [davidchang/ngReact#24]
Hi,
i am very new to react but it seems that it should be the best solution to speed up angularjs when rendering large tables.
I have following table:

```html
<table>
     <tbody ng-repeat="h in event.Heats">
        <react-component name="entrybody" props="h.Entries" />
   </tbody>
</table>
```

i am sorry for the bad formatting, but i did not find the tag for code.

The renderfunction get called as expected but without data in props, if i say props="event" i get the data. Any idea what i am doing wrong?

Kind Regards Manuel

**Comment by djett41** [comment]
@blenet are Heat and Entries React components?  Or just javascript objects in you event object which should be defined on angular $scope?

Please disregard this if you already know this, but the name attribute should refer to the React component you wish to render, and props should refer to an object on $scope which is also consistent with your React component's props

So in your HTML example, if you were to have the following object on $scope and the following React component, then everything will work properly

```javascript
  angular.module('myModule').factory('MainCtrl', function () {
    $scope.event = {
      Heats: [
        {Entries: {somePropForTheEntrybodyReactComponent: 'someValue'}},
        {Entries: {somePropForTheEntrybodyReactComponent: 'anotherValue'}},
        {Entries: {somePropForTheEntrybodyReactComponent: 'somethingElse'}}
      ]
    };

var EntryBodyComponent = React.createClass({
  propTypes: {
    somePropForTheEntrybodyReactComponent: React.PropTypes.string.isRequired
  },

  render: function() {
    var myProp = this.props.somePropForTheEntrybodyReactComponent;
    return React.DOM.div(null, myProp);
  }
});

angular.module('myModule').value( 'entrybody', EntryBodyComponent );
```

One of the main benefits of using React is that the initial rendering and updates to the DOM are alot quicker, especially vs using ng-repeat with alot of data, which probably gives the worst performance out of all angular directives.  With that being said, instead of nesting your react component inside ng-repeat, I would suggest creating a React component for the Heats List and use child components to render your list.
