### ISSUE TITLE
ngReact give “Error: module 'react' not found from …ngReact.min.js” in browserify, angular project

### ISSUE THREAD

**Issue by devdavidkarlsson** [davidchang/ngReact#83]
I am trying to include react in an existing AngularJS project. Found a bower package called ngReact. I added this and react to my project using browserify. Running grunt just give me "Error: module 'react' not found from ..../bower_components/ngReact/ngReact.min.js"

**Comment by hasdavidc** [comment]
@devdavidkarlsson My apologies for such a late response! Is this still an issue for you?

I'm honestly not very familiar with Browserify, but I think ngReact should work properly since we dealt with this issue about 6 months ago: https://github.com/davidchang/ngReact/issues/37 ; https://github.com/thetutlage/ng-react-test should show a working example with Browserify/ngReact.

**Comment by devdavidkarlsson** [comment]
Hello, I thinkt this was an issue since I used browserify together with bower, using npm only should resolve the matter:

 http://stackoverflow.com/questions/30966566/ngreact-give-error-module-react-not-found-from-ngreact-min-js-in-browser

Thank you for your reply

**Comment by hasdavidc** [comment]
Good to know - sorry for such a belated response. Closing as this has been resolved.
